from .base import Base
from .facultad import Facultad
from .localidad import Localidad
from .orientacion import Orientacion
from .especialidad import Especialidad
from .plan import Plan
from .materia import Materia
from .pais import Pais
from .universidad import Universidad
from .grado import Grado
