from .base import Base
from .grado import Grado
from .facultad import Facultad
from .localidad import Localidad
from .orientacion import Orientacion
from .plan import Plan
from .pais import Pais
from .universidad import Universidad
from .grado import Grado